[workspace]
channels = ["conda-forge", "bioconda"]
name = "igem-2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ripgrep = ">=14.1.1,<15"
nvim = ">=0.11.2,<0.12"
mask = ">=0.11.3,<0.12"
nextflow = ">=25.4.3,<26"
openjdk = ">=23.0.2,<24"
treesapp = ">=0.11.4,<0.12"
zellij = ">=0.42.2,<0.43"
cd-hit = ">=4.8.1,<5"
seqmagick = ">=0.8.6,<0.9"
